apiVersion: apps/v1
kind: Deployment
metadata:
  name: flipt-go-htmx-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flipt-go-htmx-app
  template:
    metadata:
      labels:
        app: flipt-go-htmx-app
    spec:
      containers:
        - name: flipt-go-htmx-app
          image: flipt-go-htmx-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: FLIPT_URL
              value: http://flipt:8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flipt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flipt
  template:
    metadata:
      labels:
        app: flipt
    spec:
      containers:
        - name: flipt
          image: docker.flipt.io/flipt/flipt:latest
          ports:
            - name: http
              containerPort: 8080
            - name: grpc
              containerPort: 9000
          volumeMounts:
            - name: flipt-data
              mountPath: /var/opt/flipt
      volumes:
        - name: flipt-data
          emptyDir: {}
