apiVersion: v1
kind: Service
metadata:
  name: flipt-go-htmx-app-service
spec:
  selector:
    app: flipt-go-htmx-app
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: flipt
spec:
  selector:
    app: flipt
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: grpc
      port: 9000
      targetPort: 9000
  type: LoadBalancer
